

create table cdc					
   (					
	id				text
    ,	entry_number				text
    ,	entry_title				text
    ,	entry_link				text
    ,	entry_modified				text
    ,	agencyID				text
    ,	PIID				text
    ,	modNumber				text
    ,	transactionNumber				text
    ,	signedDate				text
    ,	effectiveDate				text
    ,	currentCompletionDate				text
    ,	ultimateCompletionDate				text
    ,	obligatedAmount				text
    ,	baseAndExercisedOptionsValue				text
    ,	baseAndAllOptionsValue				text
    ,	totalObligatedAmount				text
    ,	totalBaseAndExercisedOptionsValue				text
    ,	totalBaseAndAllOptionsValue				text
    ,	contractingOfficeAgencyID				text
    ,	contractingOfficeID				text
    ,	fundingRequestingAgencyID				text
    ,	fundingRequestingOfficeID				text
    ,	foreignFunding				text
    ,	feePaidForUseOfService				text
    ,	contractActionType				text
    ,	typeOfContractPricing				text
    ,	reasonForModification				text
    ,	nationalInterestActionCode				text
    ,	costOrPricingData				text
    ,	solicitationID				text
    ,	costAccountingStandardsClause				text
    ,	descriptionOfContractRequirement				text
    ,	inherentlyGovernmentalFunction				text
    ,	GFE_GFP				text
    ,	undefinitizedAction				text
    ,	consolidatedContract				text
    ,	performanceBasedServiceContract				text
    ,	multiYearContract				text
    ,	contingencyHumanitarianPeacekeepingOperation				text
    ,	contractFinancing				text
    ,	purchaseCardAsPaymentMethod				text
    ,	numberOfActions				text
    ,	ClingerCohenAct				text
    ,	materialsSuppliesArticlesEquipment				text
    ,	laborStandards				text
    ,	constructionWageRateRequirements				text
    ,	additionalReportingValue				text
    ,	interagencyContractingAuthority				text
    ,	productOrServiceCode				text
    ,	contractBundling				text
    ,	principalNAICSCode				text
    ,	recoveredMaterialClauses				text
    ,	manufacturingOrganizationType				text
    ,	useOfEPADesignatedProducts				text
    ,	countryOfOrigin				text
    ,	placeOfManufacture				text
    ,	vendorName				text
    ,	isAlaskanNativeOwnedCorporationOrFirm				text
    ,	isAmericanIndianOwned				text
    ,	isIndianTribe				text
    ,	isNativeHawaiianOwnedOrganizationOrFirm				text
    ,	isTriballyOwnedFirm				text
    ,	isSmallBusiness				text
    ,	isVeteranOwned				text
    ,	isServiceRelatedDisabledVeteranOwnedBusiness				text
    ,	isWomenOwned				text
    ,	isMinorityOwned				text
    ,	isSubContinentAsianAmericanOwnedBusiness				text
    ,	isAsianPacificAmericanOwnedBusiness				text
    ,	isBlackAmericanOwnedBusiness				text
    ,	isHispanicAmericanOwnedBusiness				text
    ,	isNativeAmericanOwnedBusiness				text
    ,	isOtherMinorityOwned				text
    ,	isVerySmallBusiness				text
    ,	isWomenOwnedSmallBusiness				text
    ,	isEconomicallyDisadvantagedWomenOwnedSmallBusiness				text
    ,	isJointVentureWomenOwnedSmallBusiness				text
    ,	isJointVentureEconomicallyDisadvantagedWomenOwnedSmallBusiness				text
    ,	isCommunityDevelopedCorporationOwnedFirm				text
    ,	isLaborSurplusAreaFirm				text
    ,	isFederalGovernment				text
    ,	isFederallyFundedResearchAndDevelopmentCorp				text
    ,	isFederalGovernmentAgency				text
    ,	isStateGovernment				text
    ,	isLocalGovernment				text
    ,	isCityLocalGovernment				text
    ,	isCountyLocalGovernment				text
    ,	isInterMunicipalLocalGovernment				text
    ,	isLocalGovernmentOwned				text
    ,	isMunicipalityLocalGovernment				text
    ,	isSchoolDistrictLocalGovernment				text
    ,	isTownshipLocalGovernment				text
    ,	isTribalGovernment				text
    ,	isForeignGovernment				text
    ,	isCorporateEntityNotTaxExempt				text
    ,	isCorporateEntityTaxExempt				text
    ,	isPartnershipOrLimitedLiabilityPartnership				text
    ,	isSolePropreitorship				text
    ,	isSmallAgriculturalCooperative				text
    ,	isInternationalOrganization				text
    ,	isUSGovernmentEntity				text
    ,	isCommunityDevelopmentCorporation				text
    ,	isDomesticShelter				text
    ,	isEducationalInstitution				text
    ,	isFoundation				text
    ,	isHospital				text
    ,	isManufacturerOfGoods				text
    ,	isVeterinaryHospital				text
    ,	isHispanicServicingInstitution				text
    ,	receivesContracts				text
    ,	receivesGrants				text
    ,	receivesContractsAndGrants				text
    ,	isAirportAuthority				text
    ,	isCouncilOfGovernments				text
    ,	isHousingAuthoritiesPublicOrTribal				text
    ,	isInterstateEntity				text
    ,	isPlanningCommission				text
    ,	isPortAuthority				text
    ,	isTransitAuthority				text
    ,	isSubchapterSCorporation				text
    ,	isLimitedLiabilityCorporation				text
    ,	isForeignOwnedAndLocated				text
    ,	isForProfitOrganization				text
    ,	isNonprofitOrganization				text
    ,	isOtherNotForProfitOrganization				text
    ,	isShelteredWorkshop				text
    ,	stateOfIncorporation				text
    ,	countryOfIncorporation				text
    ,	organizationalType				text
    ,	is1862LandGrantCollege				text
    ,	is1890LandGrantCollege				text
    ,	is1994LandGrantCollege				text
    ,	isHistoricallyBlackCollegeOrUniversity				text
    ,	isMinorityInstitution				text
    ,	isPrivateUniversityOrCollege				text
    ,	isSchoolOfForestry				text
    ,	isStateControlledInstitutionofHigherLearning				text
    ,	isTribalCollege				text
    ,	isVeterinaryCollege				text
    ,	isAlaskanNativeServicingInstitution				text
    ,	isNativeHawaiianServicingInstitution				text
    ,	isDOTCertifiedDisadvantagedBusinessEnterprise				text
    ,	isSelfCertifiedSmallDisadvantagedBusiness				text
    ,	isSBACertifiedSmallDisadvantagedBusiness				text
    ,	isSBACertified8AProgramParticipant				text
    ,	isSelfCertifiedHUBZoneJointVenture				text
    ,	isSBACertifiedHUBZone				text
    ,	isSBACertified8AJointVenture				text
    ,	streetAddress				text
    ,	city				text
    ,	state				text
    ,	ZIPCode				text
    ,	vendorCountryCode				text
    ,	phoneNo				text
    ,	congressionalDistrictCode				text
    ,	entityDataSource				text
    ,	vendorAlternateSiteCode				text
    ,	UEI				text
    ,	UEILegalBusinessName				text
    ,	ultimateParentUEI				text
    ,	ultimateParentUEIName				text
    ,	cageCode				text
    ,	registrationDate				text
    ,	renewalDate				text
    ,	contractingOfficerBusinessSizeDetermination				text
    ,	stateCode				text
    ,	placeOfPerformanceCountryCode				text
    ,	placeOfPerformanceZIPCode				text
    ,	placeOfPerformanceCongressionalDistrict				text
    ,	extentCompeted				text
    ,	solicitationProcedures				text
    ,	typeOfSetAside				text
    ,	typeOfSetAsideSource				text
    ,	evaluatedPreference				text
    ,	numberOfOffersReceived				text
    ,	numberOfOffersSource				text
    ,	commercialItemAcquisitionProcedures				text
    ,	commercialItemTestProgram				text
    ,	A76Action				text
    ,	fedBizOpps				text
    ,	localAreaSetAside				text
    ,	subcontractPlan				text
    ,	createdBy				text
    ,	createdDate				text
    ,	lastModifiedBy				text
    ,	lastModifiedDate				text
    ,	status				text
    ,	approvedBy				text
    ,	approvedDate				text
    ,	closedStatus				text
    ,	genericString01				text
    ,	genericString02				text
    ,	genericString03				text
    ,	genericString04				text
    ,	genericString05				text
    ,	genericString06				text
    ,	genericString07				text
    ,	genericString08				text
    ,	genericString09				text
    ,	genericString10				text
    ,	referencedIDVID				text
    ,	referencedAgencyID				text
    ,	referencedPIID				text
    ,	referencedModNumber				text
    ,	referencedIDVPart8OrPart13				text
    ,	referencedIDVMultipleOrSingle				text
    ,	referencedIDVType				text
    ,	otherStatutoryAuthority				text
    ,	faxNo				text
    ,	idvTypeOfSetAside				text
    ,	statutoryExceptionToFairOpportunity				text
    ,	idvNumberOfOffersReceived				text
    ,	vendorAlternateName				text
    ,	vendorLegalOrganizationName				text
    ,	reasonNotCompeted				text
    ,	priceEvaluationPercentDifference				text
    ,	closedBy				text
    ,	closedDate				text
    ,	agencyIdentifier				text
    ,	mainAccountCode				text
    ,	subAccountCode				text
    ,	contractorName				text
    ,	streetAddress2				text
					
    )					
